kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  apiServerAddress: "{{host_ipaddress}}"
nodes:
  - role: worker
  - role: control-plane
    extraPortMappings:
      - containerPort: 5443
        hostPort: 5443
        protocol: TCP
        listenAddress: "{{host_ipaddress}}"

kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - {{host_ipaddress}}
        - 127.0.0.1
        - localhost